# SwiftLintFramework Docs: https://realm.github.io/SwiftLint/index.html

disabled_rules:
- type_name
- trailing_whitespace
- force_cast
- unused_closure_parameter

opt_in_rules:
- closure_end_indentation
- closure_spacing
- collection_alignment
- empty_count
- explicit_self
- explicit_init
- fatal_error_message
- first_where
- force_unwrapping
- implicitly_unwrapped_optional
- missing_docs
- nimble_operator
- number_separator
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- sorted_imports

excluded:
- Pods/
- Carthage/

line_length: 120

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  excluded:
    - i
    - j
    - n
    - x
    - y
